/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as pizzaPartySol from "./PizzaParty.sol";
export type { pizzaPartySol };
export type { MockVMF } from "./MockVMF";
