/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniswapPriceOracleSol from "./UniswapPriceOracle.sol";
export type { uniswapPriceOracleSol };
export type { FreePriceOracle } from "./FreePriceOracle";
export type { FreeRandomness } from "./FreeRandomness";
export type { MockVMF } from "./MockVMF";
export type { PizzaParty } from "./PizzaParty";
export type { SecureReferralSystem } from "./SecureReferralSystem";
