/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PizzaParty {
  export type GameStruct = {
    gameId: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    totalEntries: BigNumberish;
    jackpotAmount: BigNumberish;
    winners: AddressLike[];
    isCompleted: boolean;
  };

  export type GameStructOutput = [
    gameId: bigint,
    startTime: bigint,
    endTime: bigint,
    totalEntries: bigint,
    jackpotAmount: bigint,
    winners: string[],
    isCompleted: boolean
  ] & {
    gameId: bigint;
    startTime: bigint;
    endTime: bigint;
    totalEntries: bigint;
    jackpotAmount: bigint;
    winners: string[];
    isCompleted: boolean;
  };

  export type PlayerStruct = {
    totalToppings: BigNumberish;
    dailyEntries: BigNumberish;
    weeklyEntries: BigNumberish;
    lastEntryTime: BigNumberish;
    streakDays: BigNumberish;
    lastStreakUpdate: BigNumberish;
    isBlacklisted: boolean;
  };

  export type PlayerStructOutput = [
    totalToppings: bigint,
    dailyEntries: bigint,
    weeklyEntries: bigint,
    lastEntryTime: bigint,
    streakDays: bigint,
    lastStreakUpdate: bigint,
    isBlacklisted: boolean
  ] & {
    totalToppings: bigint;
    dailyEntries: bigint;
    weeklyEntries: bigint;
    lastEntryTime: bigint;
    streakDays: bigint;
    lastStreakUpdate: bigint;
    isBlacklisted: boolean;
  };

  export type ReferralStruct = {
    referrer: AddressLike;
    totalReferrals: BigNumberish;
    totalRewards: BigNumberish;
    isActive: boolean;
  };

  export type ReferralStructOutput = [
    referrer: string,
    totalReferrals: bigint,
    totalRewards: bigint,
    isActive: boolean
  ] & {
    referrer: string;
    totalReferrals: bigint;
    totalRewards: bigint;
    isActive: boolean;
  };
}

export interface PizzaPartyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DAILY_ENTRY_FEE"
      | "DAILY_PLAY_REWARD"
      | "DAILY_WINNERS_COUNT"
      | "REFERRAL_REWARD"
      | "STREAK_BONUS"
      | "VMF_HOLDING_REWARD"
      | "WEEKLY_WINNERS_COUNT"
      | "awardVMFHoldingsToppings"
      | "blacklistedAddresses"
      | "createReferralCode"
      | "currentDailyJackpot"
      | "currentWeeklyJackpot"
      | "drawDailyWinners"
      | "drawWeeklyWinners"
      | "emergencyPause"
      | "emergencyWithdraw"
      | "enterDailyGame"
      | "games"
      | "getCurrentGame"
      | "getGame"
      | "getPlayerInfo"
      | "getReferralInfo"
      | "hasEnteredToday"
      | "lastDailyDraw"
      | "lastWeeklyDraw"
      | "owner"
      | "paused"
      | "players"
      | "referralCodes"
      | "referrals"
      | "renounceOwnership"
      | "setPlayerBlacklist"
      | "transferOwnership"
      | "vmfToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DailyWinnersSelected"
      | "EmergencyPause"
      | "JackpotUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "PlayerBlacklisted"
      | "PlayerEntered"
      | "ReferralCreated"
      | "ReferralUsed"
      | "ToppingsAwarded"
      | "Unpaused"
      | "WeeklyWinnersSelected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DAILY_ENTRY_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAILY_PLAY_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAILY_WINNERS_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFERRAL_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STREAK_BONUS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VMF_HOLDING_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WEEKLY_WINNERS_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "awardVMFHoldingsToppings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistedAddresses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createReferralCode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentDailyJackpot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentWeeklyJackpot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "drawDailyWinners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "drawWeeklyWinners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enterDailyGame",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "games", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getCurrentGame",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReferralInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasEnteredToday",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastDailyDraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastWeeklyDraw",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "players",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "referralCodes",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "referrals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPlayerBlacklist",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vmfToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DAILY_ENTRY_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAILY_PLAY_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAILY_WINNERS_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFERRAL_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STREAK_BONUS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VMF_HOLDING_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WEEKLY_WINNERS_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "awardVMFHoldingsToppings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createReferralCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentDailyJackpot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentWeeklyJackpot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "drawDailyWinners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "drawWeeklyWinners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enterDailyGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "games", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferralInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasEnteredToday",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDailyDraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastWeeklyDraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "players", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "referralCodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "referrals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlayerBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vmfToken", data: BytesLike): Result;
}

export namespace DailyWinnersSelectedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    winners: AddressLike[],
    jackpotAmount: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    winners: string[],
    jackpotAmount: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    winners: string[];
    jackpotAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyPauseEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JackpotUpdatedEvent {
  export type InputTuple = [
    dailyJackpot: BigNumberish,
    weeklyJackpot: BigNumberish
  ];
  export type OutputTuple = [dailyJackpot: bigint, weeklyJackpot: bigint];
  export interface OutputObject {
    dailyJackpot: bigint;
    weeklyJackpot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerBlacklistedEvent {
  export type InputTuple = [player: AddressLike, blacklisted: boolean];
  export type OutputTuple = [player: string, blacklisted: boolean];
  export interface OutputObject {
    player: string;
    blacklisted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerEnteredEvent {
  export type InputTuple = [
    player: AddressLike,
    gameId: BigNumberish,
    entryFee: BigNumberish
  ];
  export type OutputTuple = [player: string, gameId: bigint, entryFee: bigint];
  export interface OutputObject {
    player: string;
    gameId: bigint;
    entryFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralCreatedEvent {
  export type InputTuple = [referrer: AddressLike, referralCode: string];
  export type OutputTuple = [referrer: string, referralCode: string];
  export interface OutputObject {
    referrer: string;
    referralCode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralUsedEvent {
  export type InputTuple = [
    referrer: AddressLike,
    newPlayer: AddressLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    referrer: string,
    newPlayer: string,
    reward: bigint
  ];
  export interface OutputObject {
    referrer: string;
    newPlayer: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ToppingsAwardedEvent {
  export type InputTuple = [
    player: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [player: string, amount: bigint, reason: string];
  export interface OutputObject {
    player: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeeklyWinnersSelectedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    winners: AddressLike[],
    jackpotAmount: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    winners: string[],
    jackpotAmount: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    winners: string[];
    jackpotAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PizzaParty extends BaseContract {
  connect(runner?: ContractRunner | null): PizzaParty;
  waitForDeployment(): Promise<this>;

  interface: PizzaPartyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DAILY_ENTRY_FEE: TypedContractMethod<[], [bigint], "view">;

  DAILY_PLAY_REWARD: TypedContractMethod<[], [bigint], "view">;

  DAILY_WINNERS_COUNT: TypedContractMethod<[], [bigint], "view">;

  REFERRAL_REWARD: TypedContractMethod<[], [bigint], "view">;

  STREAK_BONUS: TypedContractMethod<[], [bigint], "view">;

  VMF_HOLDING_REWARD: TypedContractMethod<[], [bigint], "view">;

  WEEKLY_WINNERS_COUNT: TypedContractMethod<[], [bigint], "view">;

  awardVMFHoldingsToppings: TypedContractMethod<[], [void], "nonpayable">;

  blacklistedAddresses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  createReferralCode: TypedContractMethod<[], [void], "nonpayable">;

  currentDailyJackpot: TypedContractMethod<[], [bigint], "view">;

  currentWeeklyJackpot: TypedContractMethod<[], [bigint], "view">;

  drawDailyWinners: TypedContractMethod<[], [void], "nonpayable">;

  drawWeeklyWinners: TypedContractMethod<[], [void], "nonpayable">;

  emergencyPause: TypedContractMethod<[pause: boolean], [void], "nonpayable">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  enterDailyGame: TypedContractMethod<
    [referralCode: string],
    [void],
    "nonpayable"
  >;

  games: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        gameId: bigint;
        startTime: bigint;
        endTime: bigint;
        totalEntries: bigint;
        jackpotAmount: bigint;
        isCompleted: boolean;
      }
    ],
    "view"
  >;

  getCurrentGame: TypedContractMethod<
    [],
    [PizzaParty.GameStructOutput],
    "view"
  >;

  getGame: TypedContractMethod<
    [gameId: BigNumberish],
    [PizzaParty.GameStructOutput],
    "view"
  >;

  getPlayerInfo: TypedContractMethod<
    [player: AddressLike],
    [PizzaParty.PlayerStructOutput],
    "view"
  >;

  getReferralInfo: TypedContractMethod<
    [player: AddressLike],
    [PizzaParty.ReferralStructOutput],
    "view"
  >;

  hasEnteredToday: TypedContractMethod<
    [player: AddressLike],
    [boolean],
    "view"
  >;

  lastDailyDraw: TypedContractMethod<[], [bigint], "view">;

  lastWeeklyDraw: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  players: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        totalToppings: bigint;
        dailyEntries: bigint;
        weeklyEntries: bigint;
        lastEntryTime: bigint;
        streakDays: bigint;
        lastStreakUpdate: bigint;
        isBlacklisted: boolean;
      }
    ],
    "view"
  >;

  referralCodes: TypedContractMethod<[arg0: string], [string], "view">;

  referrals: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        referrer: string;
        totalReferrals: bigint;
        totalRewards: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPlayerBlacklist: TypedContractMethod<
    [player: AddressLike, blacklisted: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vmfToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DAILY_ENTRY_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DAILY_PLAY_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DAILY_WINNERS_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFERRAL_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STREAK_BONUS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VMF_HOLDING_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WEEKLY_WINNERS_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "awardVMFHoldingsToppings"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blacklistedAddresses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "createReferralCode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentDailyJackpot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentWeeklyJackpot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "drawDailyWinners"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "drawWeeklyWinners"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[pause: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enterDailyGame"
  ): TypedContractMethod<[referralCode: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "games"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        gameId: bigint;
        startTime: bigint;
        endTime: bigint;
        totalEntries: bigint;
        jackpotAmount: bigint;
        isCompleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentGame"
  ): TypedContractMethod<[], [PizzaParty.GameStructOutput], "view">;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [PizzaParty.GameStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerInfo"
  ): TypedContractMethod<
    [player: AddressLike],
    [PizzaParty.PlayerStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReferralInfo"
  ): TypedContractMethod<
    [player: AddressLike],
    [PizzaParty.ReferralStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasEnteredToday"
  ): TypedContractMethod<[player: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastDailyDraw"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastWeeklyDraw"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "players"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        totalToppings: bigint;
        dailyEntries: bigint;
        weeklyEntries: bigint;
        lastEntryTime: bigint;
        streakDays: bigint;
        lastStreakUpdate: bigint;
        isBlacklisted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "referralCodes"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "referrals"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        referrer: string;
        totalReferrals: bigint;
        totalRewards: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlayerBlacklist"
  ): TypedContractMethod<
    [player: AddressLike, blacklisted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vmfToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DailyWinnersSelected"
  ): TypedContractEvent<
    DailyWinnersSelectedEvent.InputTuple,
    DailyWinnersSelectedEvent.OutputTuple,
    DailyWinnersSelectedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyPause"
  ): TypedContractEvent<
    EmergencyPauseEvent.InputTuple,
    EmergencyPauseEvent.OutputTuple,
    EmergencyPauseEvent.OutputObject
  >;
  getEvent(
    key: "JackpotUpdated"
  ): TypedContractEvent<
    JackpotUpdatedEvent.InputTuple,
    JackpotUpdatedEvent.OutputTuple,
    JackpotUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerBlacklisted"
  ): TypedContractEvent<
    PlayerBlacklistedEvent.InputTuple,
    PlayerBlacklistedEvent.OutputTuple,
    PlayerBlacklistedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerEntered"
  ): TypedContractEvent<
    PlayerEnteredEvent.InputTuple,
    PlayerEnteredEvent.OutputTuple,
    PlayerEnteredEvent.OutputObject
  >;
  getEvent(
    key: "ReferralCreated"
  ): TypedContractEvent<
    ReferralCreatedEvent.InputTuple,
    ReferralCreatedEvent.OutputTuple,
    ReferralCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralUsed"
  ): TypedContractEvent<
    ReferralUsedEvent.InputTuple,
    ReferralUsedEvent.OutputTuple,
    ReferralUsedEvent.OutputObject
  >;
  getEvent(
    key: "ToppingsAwarded"
  ): TypedContractEvent<
    ToppingsAwardedEvent.InputTuple,
    ToppingsAwardedEvent.OutputTuple,
    ToppingsAwardedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WeeklyWinnersSelected"
  ): TypedContractEvent<
    WeeklyWinnersSelectedEvent.InputTuple,
    WeeklyWinnersSelectedEvent.OutputTuple,
    WeeklyWinnersSelectedEvent.OutputObject
  >;

  filters: {
    "DailyWinnersSelected(uint256,address[],uint256)": TypedContractEvent<
      DailyWinnersSelectedEvent.InputTuple,
      DailyWinnersSelectedEvent.OutputTuple,
      DailyWinnersSelectedEvent.OutputObject
    >;
    DailyWinnersSelected: TypedContractEvent<
      DailyWinnersSelectedEvent.InputTuple,
      DailyWinnersSelectedEvent.OutputTuple,
      DailyWinnersSelectedEvent.OutputObject
    >;

    "EmergencyPause(bool)": TypedContractEvent<
      EmergencyPauseEvent.InputTuple,
      EmergencyPauseEvent.OutputTuple,
      EmergencyPauseEvent.OutputObject
    >;
    EmergencyPause: TypedContractEvent<
      EmergencyPauseEvent.InputTuple,
      EmergencyPauseEvent.OutputTuple,
      EmergencyPauseEvent.OutputObject
    >;

    "JackpotUpdated(uint256,uint256)": TypedContractEvent<
      JackpotUpdatedEvent.InputTuple,
      JackpotUpdatedEvent.OutputTuple,
      JackpotUpdatedEvent.OutputObject
    >;
    JackpotUpdated: TypedContractEvent<
      JackpotUpdatedEvent.InputTuple,
      JackpotUpdatedEvent.OutputTuple,
      JackpotUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlayerBlacklisted(address,bool)": TypedContractEvent<
      PlayerBlacklistedEvent.InputTuple,
      PlayerBlacklistedEvent.OutputTuple,
      PlayerBlacklistedEvent.OutputObject
    >;
    PlayerBlacklisted: TypedContractEvent<
      PlayerBlacklistedEvent.InputTuple,
      PlayerBlacklistedEvent.OutputTuple,
      PlayerBlacklistedEvent.OutputObject
    >;

    "PlayerEntered(address,uint256,uint256)": TypedContractEvent<
      PlayerEnteredEvent.InputTuple,
      PlayerEnteredEvent.OutputTuple,
      PlayerEnteredEvent.OutputObject
    >;
    PlayerEntered: TypedContractEvent<
      PlayerEnteredEvent.InputTuple,
      PlayerEnteredEvent.OutputTuple,
      PlayerEnteredEvent.OutputObject
    >;

    "ReferralCreated(address,string)": TypedContractEvent<
      ReferralCreatedEvent.InputTuple,
      ReferralCreatedEvent.OutputTuple,
      ReferralCreatedEvent.OutputObject
    >;
    ReferralCreated: TypedContractEvent<
      ReferralCreatedEvent.InputTuple,
      ReferralCreatedEvent.OutputTuple,
      ReferralCreatedEvent.OutputObject
    >;

    "ReferralUsed(address,address,uint256)": TypedContractEvent<
      ReferralUsedEvent.InputTuple,
      ReferralUsedEvent.OutputTuple,
      ReferralUsedEvent.OutputObject
    >;
    ReferralUsed: TypedContractEvent<
      ReferralUsedEvent.InputTuple,
      ReferralUsedEvent.OutputTuple,
      ReferralUsedEvent.OutputObject
    >;

    "ToppingsAwarded(address,uint256,string)": TypedContractEvent<
      ToppingsAwardedEvent.InputTuple,
      ToppingsAwardedEvent.OutputTuple,
      ToppingsAwardedEvent.OutputObject
    >;
    ToppingsAwarded: TypedContractEvent<
      ToppingsAwardedEvent.InputTuple,
      ToppingsAwardedEvent.OutputTuple,
      ToppingsAwardedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WeeklyWinnersSelected(uint256,address[],uint256)": TypedContractEvent<
      WeeklyWinnersSelectedEvent.InputTuple,
      WeeklyWinnersSelectedEvent.OutputTuple,
      WeeklyWinnersSelectedEvent.OutputObject
    >;
    WeeklyWinnersSelected: TypedContractEvent<
      WeeklyWinnersSelectedEvent.InputTuple,
      WeeklyWinnersSelectedEvent.OutputTuple,
      WeeklyWinnersSelectedEvent.OutputObject
    >;
  };
}
